DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS
(
ID          INT PRIMARY KEY auto_increment,
USERNAME    VARCHAR,
PASSWORD    VARCHAR,
ROLE        VARCHAR
);

DROP TABLE IF EXISTS USER_TEAM;

CREATE TABLE USER_TEAM
(
ID          INT PRIMARY KEY auto_increment,
USERNAME    VARCHAR,
TEAM_NAME   VARCHAR
);

DROP TABLE IF EXISTS ACL_P_OBJECT;

CREATE TABLE POKEMON_ACL
(
ID              INT AUTO_INCREMENT PRIMARY KEY,
POKEMON_ID      INT,
TEAM_NAME       VARCHAR,
AC_ROLE_NAME    VARCHAR
);


