version: "3.3"
services:
  opa:
    image: openpolicyagent/opa
    ports:
      - "8181:8181"
    volumes:
      - ./policy/policy.rego:/policy/policy.rego:ro
    command:
      - "run"
      - "--server"
      - "--log-format=json-pretty"
      - "--set=decision_logs.console=true"
      - "/policy/policy.rego"
